config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  get 'broadband/search' => 'broadband#search', as: 'search_broadband'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @search_results = Broadband_Wrapper.search_broadband(@search_term)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <%=stylesheet_link_tag "application", media: "screen" %>

    <title>Dude, What's my speed?</title>
  </head>
  <body>

  <!-- Navbar -->
         <div class="navbar navbar-default navbar-fixed-top">
           <div class="container">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
             </button>

             <a class="navbar-brand text-muted" href="#">Dude What's My Speed?</a>
             <div class="collapse navbar-collapse">

               <ul class="nav navbar-nav navbar-right">
                 <li><a href="#">Log In</a></li>

                 <li class="dropdown">
                   <a data-toggle="dropdown" data-target="#">Home<b class="caret">
                   </b></a>
                   <ul class="dropdown-menu">
                     <li><a href="#">Who</a></li>
                     <li><a href="#">What</a></li>
                     <li><a href="#">Where</a></li>
                     <li class="divider"></li>
                     <li><a href="#">Use RasberryPi to Track Internet Speeds</a></li>
                   </ul>
                 </li>
               </ul>

             </div>
           </div>
         </div> <!-- End navbar -->

          <div class="col-sm-10">
            <h3>Find Your ISP Speeds</h3>
              <%= form_tag(search_broadband_path(), :method => "get") do %>
                <%= search_field_tag("query", nil, :placeholder => "search broadband") %>
                <%= submit_tag "Submit", :name => nil, class: "button" %>
              <% end %>
          </div>

         <footer class="footer">
           <div class="container">
             <p class="text-muted">&copy; 2017 DudeWhatsMySpeed? - By Trish Griego
           </p>
           </div>
         </footer>
     <%=javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatsMySpeed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>